---
# This action will cut a release based on a tagged commit that starts with "v"
name: "Publish Artifacts to Github"

"on":
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - "v*"

jobs:
  publish_python:
    name: "Publish Python Artifacts"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "./.github/actions/setup-environment"
      - name: "Set version environment variable"
        run: "echo RELEASE_VERSION=${GITHUB_REF:10} >> $GITHUB_ENV"
      - name: "Run uv build"
        run: "uv build"
      - name: "Publish to PyPI"
        run: "uv publish"
        env:
          UV_PUBLISH_TOKEN: "${{ secrets.PYPI_API_TOKEN }}"
      - name: "Upload binaries to release"
        uses: "softprops/action-gh-release@v1"
        with:
          files: "dist/*"
          generate_release_notes: true
  publish_container:
    name: "Publish Container Artifacts"
    runs-on: "ubuntu-latest"
    env:
      REGISTRY: "ghcr.io"
      IMAGE_NAME: "${{ github.repository }}"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Set release name environment variable"
        run: "echo RELEASE_NAME=${GITHUB_REF:10} >> $GITHUB_ENV"
      - name: "Set release version environment variable"
        run: "echo RELEASE_VERSION=${GITHUB_REF:11} >> $GITHUB_ENV"
      - name: "Gather Docker metadata"
        id: "meta"
        uses: "docker/metadata-action@v5"
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: "Login to ghcr.io"
        uses: "docker/login-action@v3"
        with:
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Build and push container"
        uses: "docker/build-push-action@v5"
        with:
          context: "."
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
    needs:
      - "publish_python"
